# Generated by Django 5.1.5 on 2026-01-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_preview_url',
            field=models.URLField(help_text='Short teaser video URL', max_length=1000),
        ),
    ]
